# Generated by Django 4.2.13 on 2024-07-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='权限名')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='权限代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150, unique=True, verbose_name='角色名')),
                ('description', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=150, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=15, verbose_name='手机号')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='UserLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录尝试次数')),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True, verbose_name='最后尝试时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_user_lock',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='令牌')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_token',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('client_ip', models.GenericIPAddressField(verbose_name='客户端IP')),
                ('login_status', models.BooleanField(default=False, verbose_name='登录状态')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录失败原因')),
                ('browser_info', models.CharField(max_length=255, verbose_name='浏览器信息')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_login_log',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.role', verbose_name='角色')),
            ],
            options={
                'db_table': 't_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
