# Generated by Django 4.2.13 on 2024-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='os_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='操作系统信息'),
        ),
    ]
