# Generated by Django 4.2.13 on 2024-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_commandlog_alter_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='执行主机IP'),
        ),
    ]
