# Generated by Django 4.2.13 on 2024-10-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_commandlog_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='告警联系人名称')),
                ('creator', models.CharField(max_length=150, verbose_name='创建人')),
                ('notify_type', models.CharField(max_length=50, verbose_name='通知类型')),
                ('webhook', models.URLField(max_length=255, verbose_name='Webhook链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_alert_contacts',
            },
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用'),
        ),
    ]
