# Generated by Django 4.2.13 on 2024-07-31 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_loginlog_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('user', 'role', 'permission')},
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
