# Generated by Django 4.2.13 on 2024-07-31 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_rolepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
