# Generated by Django 4.2.13 on 2024-10-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_alertcontact_name_commandalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandalert',
            name='alert_contacts',
        ),
        migrations.AddField(
            model_name='commandalert',
            name='alert_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.alertcontact', verbose_name='告警联系人'),
        ),
        migrations.RemoveField(
            model_name='commandalert',
            name='hosts',
        ),
        migrations.AddField(
            model_name='commandalert',
            name='hosts',
            field=models.ManyToManyField(to='apps.host', verbose_name='关联主机'),
        ),
    ]
