# Generated by Django 4.2.13 on 2024-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_rolepermission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=500, verbose_name='令牌'),
        ),
    ]
