# Generated by Django 4.2.13 on 2024-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_commandalert_alert_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandalert',
            name='alert_contact',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='告警联系人'),
        ),
        migrations.AlterField(
            model_name='commandalert',
            name='command_rule',
            field=models.TextField(blank=True, null=True, verbose_name='命令规则'),
        ),
        migrations.RemoveField(
            model_name='commandalert',
            name='hosts',
        ),
        migrations.AlterField(
            model_name='commandalert',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否告警'),
        ),
        migrations.AddField(
            model_name='commandalert',
            name='hosts',
            field=models.TextField(blank=True, null=True, verbose_name='关联主机'),
        ),
    ]
