# Generated by Django 4.2.13 on 2024-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_commandalert_alert_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandalert',
            name='alert_contact',
        ),
        migrations.AddField(
            model_name='commandalert',
            name='alert_contacts',
            field=models.ManyToManyField(blank=True, null=True, to='apps.alertcontact', verbose_name='告警联系人'),
        ),
        migrations.RemoveField(
            model_name='commandalert',
            name='hosts',
        ),
        migrations.AddField(
            model_name='commandalert',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, to='apps.host', verbose_name='关联主机'),
        ),
    ]
