# Generated by Django 4.2.13 on 2024-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlock',
            name='lock_count',
            field=models.IntegerField(default=0, verbose_name='尝试锁定次数'),
        ),
    ]
