# Generated by Django 4.2.13 on 2024-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_userlock_lock_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='凭据名称')),
                ('type', models.CharField(choices=[('password', 'Password'), ('key', 'Key'), ('api_key', 'API Key')], max_length=50, verbose_name='凭据类型')),
                ('account', models.CharField(blank=True, max_length=150, null=True, verbose_name='账户')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('key', models.TextField(blank=True, null=True, verbose_name='密钥')),
                ('key_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密钥密码')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_credential',
            },
        ),
    ]
