# Generated by Django 4.2.13 on 2024-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(max_length=50, verbose_name='凭据类型'),
        ),
    ]
