# Generated by Django 4.2.13 on 2024-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_commandalert_alert_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandalert',
            name='match_type',
            field=models.CharField(choices=[('exact', '精准匹配'), ('fuzzy', '模糊匹配')], default='exact', max_length=20, verbose_name='匹配类型'),
        ),
    ]
