# Generated by Django 4.2.13 on 2024-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_credential_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='api_key',
        ),
        migrations.AddField(
            model_name='credential',
            name='Key_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='credential',
            name='Key_Secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Secret'),
        ),
    ]
