# Generated by Django 4.2.13 on 2024-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_commandalert_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_level',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '开启')], default=0, verbose_name='MFA认证等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='OTP密钥'),
        ),
        migrations.AlterField(
            model_name='commandalert',
            name='match_type',
            field=models.CharField(choices=[('exact', '精匹配'), ('fuzzy', '模糊匹配')], default='exact', max_length=20, verbose_name='匹配类型'),
        ),
    ]
