# Generated by Django 4.2.13 on 2024-08-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_credential_api_key_credential_key_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='Key_ID',
            new_name='KeyId',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='Key_Secret',
            new_name='KeySecret',
        ),
    ]
