# Generated by Django 4.2.13 on 2024-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='multi_login_account',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='多人登录账号'),
        ),
    ]
