# Generated by Django 4.2.13 on 2024-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_rename_key_id_credential_keyid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='监控名称')),
                ('domain', models.CharField(max_length=255, verbose_name='域名')),
                ('type', models.CharField(max_length=50, verbose_name='监控类型')),
                ('connectivity', models.BooleanField(default=False, verbose_name='连通性')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('redirection', models.CharField(blank=True, max_length=255, null=True, verbose_name='重定向地址')),
                ('time_consumption', models.FloatField(blank=True, null=True, verbose_name='耗时（秒）')),
                ('dns', models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS 信息')),
                ('tls_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='TLS 版本')),
                ('http_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='HTTP 版本')),
                ('certificate_days', models.IntegerField(blank=True, null=True, verbose_name='证书剩余天数')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('alert', models.BooleanField(default=False, verbose_name='告警')),
                ('monitor_frequency', models.IntegerField(default=60, verbose_name='监控频率（秒）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_domain_monitor',
            },
        ),
    ]
