# Generated by Django 4.2.13 on 2024-08-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_domainmonitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmonitor',
            name='type',
        ),
    ]
