# Generated by Django 4.2.13 on 2024-11-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_systemsettings_multi_login_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='最后活动时间'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='用户'),
        ),
    ]
