# Generated by Django 4.2.13 on 2024-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_token_last_activity_alter_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
