# Generated by Django 4.2.13 on 2024-08-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_domainmonitor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmonitor',
            name='dns',
        ),
    ]
