# Generated by Django 4.2.13 on 2024-08-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_domainmonitor_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='主机名称')),
                ('status', models.BooleanField(default=False, verbose_name='连接状态')),
                ('node', models.CharField(max_length=255, verbose_name='节点')),
                ('operating_system', models.CharField(max_length=50, verbose_name='操作系统')),
                ('network', models.GenericIPAddressField(verbose_name='IP地址')),
                ('protocol', models.CharField(max_length=10, verbose_name='协议')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.credential', verbose_name='关联凭据')),
            ],
            options={
                'db_table': 't_host',
            },
        ),
    ]
