# Generated by Django 4.2.13 on 2024-12-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_remove_token_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=150, verbose_name='告警名称')),
                ('alert_rule', models.TextField(verbose_name='告警规则')),
                ('alert_contacts', models.TextField(verbose_name='告警联系人')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
            ],
            options={
                'db_table': 't_alert_history_log',
            },
        ),
    ]
