from django.urls import path
from apps.views import LoginView, MFABindView, UserListView, RolesPermissionsView, CreateUserView, UserUpdateView, LoginLogView, UserDetailView, OperationLogView, LockRecordView, CredentialView, DomainMonitorView, HostView, CredentialSelectionView, TestConnectionView, NodeSelectionView, get_tree_structure,FileListView, FileUploadView, FileDownloadView, CommandLogView, AlertContactView, CommandAlertView, AlertContactList, HostListView, AssetNodesView, dashboard_statistics, login_statistics, LogoutView, FileDownloadContentView, AlertHistoryLogView
from apps.views.system_settings import SystemSettingsView

urlpatterns = [
    path('api/login/', LoginView.as_view(), name='login'),
    path('api/mfa/bind/', MFABindView.as_view(), name='mfa_bind'),
    path('api/users/create/', CreateUserView.as_view(), name='user-create'),
    path('api/users/', UserListView.as_view(), name='user-list'),
    path('api/users/<str:username>/detail/', UserDetailView.as_view(), name='user-detail'),
    path('api/users/<str:username>/lock/', UserDetailView.as_view(), name='user-lock'),
    path('api/users/<str:username>/reset_password/', UserDetailView.as_view(), name='reset-password'),
    path('api/users/<str:username>/delete/', UserDetailView.as_view(), name='user-delete'),
    path('api/users/<str:username>/update/', UserUpdateView.as_view(), name='user-update'),
    path('api/roles_permissions/', RolesPermissionsView.as_view(), name='roles-permissions'),
    path('api/login_logs/', LoginLogView.as_view(), name='login-log'),
    path('api/operation_logs/', OperationLogView.as_view(), name='operation-log'),
    path('api/lock_record/', LockRecordView.as_view(), name='lock-record'),
    path('api/credentials/', CredentialView.as_view(), name='credentials-list'),
    path('api/credentials/create/', CredentialView.as_view(), name='credentials-create'),
    path('api/credentials/<int:pk>/delete/', CredentialView.as_view(), name='credentials-delete'),
    path('api/credentials/<int:pk>/update/', CredentialView.as_view(), name='credentials-update'),
    path('api/monitor_domains/', DomainMonitorView.as_view(), name='domain-monitor'),
    path('api/monitor_domains/create/', DomainMonitorView.as_view(), name='domain-monitor-create'),
    path('api/monitor_domains/<int:pk>/update/', DomainMonitorView.as_view(), name='domain-monitor-update'),
    path('api/monitor_domains/<int:pk>/delete/', DomainMonitorView.as_view(), name='domain-monitor-delete'),
    path('api/monitor_domains/<int:pk>/', DomainMonitorView.as_view(), name='monitor-domain-detail'),
    path('api/nodes/', NodeSelectionView.as_view(), name='node-selection'),
    path('api/hosts/test_connection/', TestConnectionView.as_view(), name='test-connection'),
    path('api/hosts/', HostView.as_view(), name='hosts-list'),
    path('api/hosts/create/', HostView.as_view(), name='hosts-create'),
    path('api/hosts/<str:pk>/update/', HostView.as_view(), name='hosts-update'),
    path('api/hosts/<str:pk>/delete/', HostView.as_view(), name='hosts-delete'),
    path('api/hosts/<str:pk>/', HostView.as_view(), name='host-detail'),
    path('api/hosts/credentials_selection/', CredentialSelectionView.as_view(), name='credential-selection'),
    path('api/terminal/get_tree_structure/', get_tree_structure, name='get_tree_structure'),
    path('api/terminal/files/<str:host_id>/', FileListView.as_view()),
    path('api/terminal/upload/<str:host_id>/', FileUploadView.as_view()),
    path('api/terminal/download/<str:host_id>/', FileDownloadView.as_view()),
    path('api/command_logs/', CommandLogView.as_view(), name='command_logs'),
    path('api/alert_contacts/', AlertContactView.as_view(), name='alert_contacts-list'),
    path('api/alert_contacts/create/', AlertContactView.as_view(), name='alert_contacts-create'),
    path('api/alert_contacts/<str:name>/update/', AlertContactView.as_view(), name='update_alert_contact'),
    path('api/alert_contacts/<str:name>/delete/', AlertContactView.as_view(), name='delete_alert_contact'),
    path('api/command_alerts/', CommandAlertView.as_view(), name='command-alert-list'),
    path('api/command_alerts/create/', CommandAlertView.as_view(), name='command-alert-create'),
    path('api/command_alerts/<int:id>/', CommandAlertView.as_view(), name='command-alert-detail'),
    path('api/command_alerts/<int:id>/update/', CommandAlertView.as_view(), name='command-alert-update'),
    path('api/command_alerts/<int:id>/delete/', CommandAlertView.as_view(), name='command-alert-delete'),
    path('api/command_alerts/hosts/', HostListView.as_view(), name='host-list'),
    path('api/command_alerts/alert_contacts/', AlertContactList.as_view(), name='alert-contact-list'),
    path('api/asset_nodes/', AssetNodesView.as_view(), name='asset-nodes'),
    path('api/asset_nodes/<str:pk>/', AssetNodesView.as_view(), name='asset-node-detail'),
    path('api/settings/system/', SystemSettingsView.as_view(), name='system-settings'),
    path('api/dashboard/statistics/', dashboard_statistics, name='dashboard-statistics'),
    path('api/dashboard/login_statistics/<str:days>/', login_statistics, name='login-statistics'),
    path('api/logout/', LogoutView.as_view(), name='logout'),
    path('api/terminal/download_file/<str:transfer_id>/', FileDownloadContentView.as_view()),
    path('api/alert_history_logs/', AlertHistoryLogView.as_view(), name='alert-history-logs'),
]
